Single Sensors package for DVL + IMU + depth sensor
mcgill-robotics/AUV-2025 pull request #321
Opened 2023-10-16 21:57 UTC by vivekandathil

## Related Issue(s)
  - Issue #223 

## Other Dependent PRs

## Changes Made
- Created a sensors/ package with combined CMakeLists.txt & package.xml file
- Moved related DVL + IMU + Depth Sensor files into the sensors package

## Rationale/Other Solutions Considered

## Tests Done
- Verified `catkin build` runs successfully (now with 15 packages instead of 17)

## Optional Screen Recording

## Required Wiki Changes (if any)

## Required install_dependencies.sh Changes (if any)

## Related Branches (other than one that will be merged)

2023-10-16 22:00 UTC, antoinedang commented on catkin_ws/src/sensors/depth_sensor/.placeholder
don't need this folder if it just has an empty file inside it

2023-10-16 22:01 UTC, antoinedang commented on catkin_ws/src/sensors/CMakeLists.txt
> +  rosserial_arduino
I think you're missing rospy in these dependencies (the imu has rospy in this part of the CMakeLists

2023-10-16 22:01 UTC, antoinedang commented on catkin_ws/src/sensors/CMakeLists.txt
> +  rosserial_arduino
same for the find_package() part as well

2023-10-16 22:03 UTC, MrMondrian commented on catkin_ws/src/auv-sim-gazebo
This submodule change would be breaking for docker on windows. @antoinedang I think we need a way to make the submodules always default to the latest commit on noetic.

For now this can be fixed by pulling the gazebo sim and commit the submodule changes again

2023-10-16 22:04 UTC, MrMondrian commented
Ignore the failing integration test it doesn't mean anything

2023-10-16 22:10 UTC, antoinedang requested changes
Not sure I'm a fan of the seperate folders per-sensor, since they only have one (or zero) files in them. I think it would be cleaner to have a src/ and config/ folder in the top level with no subdirectories for sensors. Could you also make a README.md for the package (can be super short, just a brief description of what the package does)? Also, I think you forgot to update the imu.launch file (it looks for the imu config file using $(find imu)) which would cause an error. Last thing would be the CMakeLists.txt file is a bit of a mess with a lot of repeated parts, could you make sure any parts that are repeated are combined into one part (if possible) to make it more readable. Other than that good job and really quick too, gg

2023-10-16 22:11 UTC, antoinedang commented on catkin_ws/src/auv-sim-gazebo
Yes, I agree I was about to say. I assumed that adding it to the gitignore would fix that stuff but apparently not

2023-10-16 22:11 UTC, antoinedang commented
damn you made those changes quick af lmao, good shit

2023-10-16 22:12 UTC, antoinedang commented
> Ignore the failing integration test it doesn't mean anything

It does @vivekandathil, you can ignore the CI if it fails the "settle" part of CI but for "catkin build" thats something to fix.

2023-10-16 22:15 UTC, MrMondrian commented
Oh I didn’t look to closely because it’s been failing on the settle test for some reason. The catkin build test is reliable

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Antoine Dangeard ***@***.***>
Sent: Monday, October 16, 2023 5:12:59 PM
To: mcgill-robotics/AUV-2024 ***@***.***>
Cc: Anthony Tan ***@***.***>; Review requested ***@***.***>
Subject: Re: [mcgill-robotics/AUV-2024] Single Sensors package for DVL + IMU + depth sensor (PR #321)


Ignore the failing integration test it doesn't mean anything

It does @vivekandathil<https://github.com/vivekandathil>, you can ignore the CI if it fails the "settle" part of CI but for "catkin build" thats something to fix.

—
Reply to this email directly, view it on GitHub<https://github.com/mcgill-robotics/AUV-2024/pull/321#issuecomment-1765355800>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ANZEUAQORFQDZU6DAJ4UDCLX7WWOXAVCNFSM6AAAAAA6C3HX3SVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTONRVGM2TKOBQGA>.
You are receiving this because your review was requested.Message ID: ***@***.***>

2023-10-16 22:24 UTC, MrMondrian commented
The integration test appears to be failing because the state estimation package is looking for the depth sensor package.

2023-10-17 01:34 UTC, MrMondrian commented
@vivekandathil the state estimation [launch file](https://github.com/mcgill-robotics/AUV-2024/blob/d040bcae486b1334f8bb2d87d1dd2a03fdd3acf9/catkin_ws/src/state_estimation/launch/state_estimation.launch#L4-L5) will also need to be modified as it looks for the dvl and imu launch files in the old packages.

2023-10-17 23:07 UTC, MrMondrian requested changes

2023-10-17 23:07 UTC, MrMondrian commented on catkin_ws/src/state_estimation/launch/state_estimation.launch
> +		<include file="../../sensors/launch/dvl.launch"/>
Would be better to do `$(find sensors)`

2023-10-18 01:28 UTC, MrMondrian requested changes

2023-10-18 01:28 UTC, MrMondrian commented on catkin_ws/src/sensors/launch/imu.launch
> +		<rosparam command="load" file="../config/sbg_imu.yaml"/>
this should be `$(find sensors)`

2023-10-18 15:29 UTC, MrMondrian requested changes

2023-10-18 15:29 UTC, MrMondrian commented on catkin_ws/src/sensors/launch/dvl.launch
I pulled the branch and tested state_estimation.launch. Line 6: `pkg="dvl"`. This causes a bug and needs to be updated to `pkg="sensors"`.

2023-10-18 15:30 UTC, MrMondrian commented on catkin_ws/src/sensors/launch/dvl.launch
I'm reasonably confident this will be the last change necessary

2023-10-18 15:38 UTC, MrMondrian approved these changes

2023-10-18 18:58 UTC, antoinedang commented on catkin_ws/src/state_estimation/launch/state_estimation.launch
> +		<include file="$(find sensors)/launch/dvl.launch"/>
I think this should also include the depth sensor launch file? (I see that it wasnt there before but that might have been a bug we hadnt found yet) Correct me if im wrong @MrMondrian

2023-10-18 18:59 UTC, MrMondrian commented
We probably commented it out at comp after the depth sensor broke

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Antoine Dangeard ***@***.***>
Sent: Wednesday, October 18, 2023 2:58:47 PM
To: mcgill-robotics/AUV-2024 ***@***.***>
Cc: Anthony Tan ***@***.***>; Mention ***@***.***>
Subject: Re: [mcgill-robotics/AUV-2024] Single Sensors package for DVL + IMU + depth sensor (PR #321)


@antoinedang commented on this pull request.

________________________________

In catkin_ws/src/state_estimation/launch/state_estimation.launch<https://github.com/mcgill-robotics/AUV-2024/pull/321#discussion_r1364373970>:

> @@ -1,8 +1,8 @@
 <launch>
     <arg name="sim" default="false" />
     <group unless="$(arg sim)">
-               <include file="$(find imu)/launch/imu.launch"/>
-               <include file="$(find dvl)/launch/dvl.launch"/>
+               <include file="$(find sensors)/launch/imu.launch"/>
+               <include file="$(find sensors)/launch/dvl.launch"/>


I think this should also include the depth sensor launch file? (I see that it wasnt there before but that might have been a bug we hadnt found yet) Correct me if im wrong @MrMondrian<https://github.com/MrMondrian>

—
Reply to this email directly, view it on GitHub<https://github.com/mcgill-robotics/AUV-2024/pull/321#pullrequestreview-1685879494>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ANZEUARQCW4Y7FOLZ4QET2LYAARGPAVCNFSM6AAAAAA6C3HX3SVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTMOBVHA3TSNBZGQ>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-10-18 19:18 UTC, antoinedang requested changes
can you just add the depth sensor launch file to the state estimation launch file? After that all good

2023-10-19 19:09 UTC, antoinedang approved these changes

2023-10-19 19:10 UTC, merged