Renaming topics mohamed
mcgill-robotics/AUV-2025 pull request #387
Opened 2023-11-15 02:10 UTC by moh-abdelhady04

## Related Issue(s)
(https://github.com/mcgill-robotics/AUV-2024/issues/218)

## Other Dependent PRs
  - auv-sim-gazebo PR

## Changes Made
- Renamed the topics as per instructions. All details mentioned in commit messages.

## Rationale/Other Solutions Considered

## Tests Done

## Optional Screen Recording

## Required Wiki Changes (if any)
- Update any topic names that are on the wiki

## Required install_dependencies.sh Changes (if any)

## Related Branches (other than one that will be merged)

2023-11-15 14:16 UTC, frompotenza commented
Have you done any tests?

2023-11-16 01:45 UTC, frompotenza requested changes

2023-11-16 01:45 UTC, frompotenza commented on catkin_ws/src/controls/src/superimposer.py
>          self.pitch = Superimposer.Degree_Of_Freedom('pitch')
what about heave, roll, and pitch?

2023-11-16 17:54 UTC, antoinedang commented on catkin_ws/src/controls/src/servers/base_server.py
>          self.pub_pitch = rospy.Publisher('pitch', Float64, queue_size=1)
missed pitch here

2023-11-16 17:55 UTC, antoinedang commented
@moh-abdelhady04 could you link to the list of all the topics you changed? Would make reviewing this easier

2023-12-05 06:36 UTC, frompotenza commented
For some topics, it's like state_x and for others is state/x (this is just an example, not that there is a topic named state_x). Is that on purpose?

2023-12-06 21:07 UTC, antoinedang commented
tests complete: additional integration tests (pending PR but tested locally), run sim + check all topic names that show up

passed all of them so I'm gonna merge

2023-12-06 21:07 UTC, merged