add hydrophones
mcgill-robotics/AUV-2025 pull request #455
Opened 2024-01-11 22:48 UTC by frompotenza

Add hydrophones to the code. It is not in a catkin package, so it's not going to cause any problems. I'm PRing early because the sim already has the hydrophones msgs. So, if anyone tries to test ros stuff in the sim, they'll get an error

2024-01-11 23:02 UTC, MrMondrian commented
is that @Rain1618's code or legacy code

2024-01-11 23:02 UTC, MrMondrian approved these changes

2024-01-11 23:52 UTC, frompotenza commented
> is that @Rain1618's code or legacy code

it's her code

2024-01-12 00:17 UTC, antoinedang requested changes

2024-01-12 00:17 UTC, antoinedang commented on catkin_ws/src/auv_msgs/msg/UnityState.msg
> +geometry_msgs/Vector3 pinger1
can we rename to something clearer? like dt_pinger1 or dt_20kHz or some shit

2024-01-12 00:25 UTC, closed without merging