Buoyancy Offset with rospy.topics
mcgill-robotics/AUV-2025 pull request #505
Opened 2024-02-03 18:15 UTC by epicgamer17

## Related Issue(s)
  - Issue #1
  - Issue #2

## Other Dependent PRs
  - PR #2
  - PR #3

## Changes Made
- Describe the changes made in this PR.

## Rationale/Other Solutions Considered
- Explain the rationale behind this PR.
- Mention any alternative solutions considered (if any).

## Tests Done
- Describe the tests that have been performed.
- Mention any relevant test cases or scenarios.

## Optional Screen Recording
Attach a screen recording of test run(s) (if applicable).

## Required Wiki Changes (if any)
- List any changes that need to be made to the project's wiki (if applicable).

## Required install_dependencies.sh Changes (if any)
- List any new dependencies that need to be installed by the install_dependencies.sh script

## Related Branches (other than one that will be merged)
- List any related branches (if applicable).

2024-02-03 19:24 UTC, MrMondrian commented
@epicgamer17 did you test this? the integration tests are failing

2024-02-12 16:17 UTC, antoinedang commented
@epicgamer17 whats the status on this PR? been open for a super long time, what's taking so long?

2024-02-12 16:18 UTC, antoinedang commented on catkin_ws/src/controls/src/servers/state_quaternion_pid_server.py
> +from std_msgs.msg import Bool, String
why is the String import needed?

2024-02-12 16:22 UTC, antoinedang commented on catkin_ws/src/controls/src/servers/state_quaternion_pid_server.py
> +            self.buoyant_force_pub.publish(Bool(True))
code looks good, I'd just reverse the logic for safety (buoyant force is off when a pose is received, and only turned on if there is a Z position goal which is below the z threshold). I think the way it is written now, even if the goal does not contain a Z position target (for example it just sets the Y position or the quaternion), the buoyancy force will activate, even though the AUV's Z position might not be below the threshold.

2024-02-12 16:23 UTC, antoinedang requested changes
see comments

2024-03-04 17:40 UTC, closed without merging